/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubesperpustakaan;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class Petugas extends javax.swing.JFrame {
private Statement st;
private Connection Con;
private ResultSet Rs;
private String tampilan="yyyy-MM-dd";
private String Sql="";
private String host;
public String kodepetugas,namapetugas,tanggallahir,tempatlahir,jeniskelamin,jabatan,alamat,nohp,Tanggal;
    /**
     * Creates new form Petugas
     */
    public Petugas() {
        initComponents();
        KoneksiPetugas();
        TampilPetugas("SELECT*FROM tb_petugas");
        kosongkan();
    }
    private void KoneksiPetugas(){
        try {
        Class.forName("com.mysql.jdbc.Driver");    //Jika Tidak Terjadi Error
        Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_perpustakaan","root","");
            System.out.println("Connection Succes");
            JOptionPane.showMessageDialog(null, "Connection Succes");
        } catch (Exception e) {
            System.out.println("Connection Failed"+e);
            JOptionPane.showMessageDialog(null, "Connection failed");
        }
    }
     private void TampilPetugas(String Sql){
        DefaultTableModel  grid=new DefaultTableModel();
        grid.addColumn("No");
        grid.addColumn("Kode Petugas");
        grid.addColumn("Nama Petugas");
        grid.addColumn("Tanggal Lahir");
        grid.addColumn("Tempat Lahir");
        grid.addColumn("Jenis Kelamin");
        grid.addColumn("Jabatan");
        grid.addColumn("Alamat");
        grid.addColumn("No.Hp");
        try {
            int i=1;
            st=Con.createStatement();
            Rs=st.executeQuery("SELECT*FROM tb_petugas");
            while (Rs.next()){
                grid.addRow(new Object[]{
                    (""+i++),Rs.getString(1),
                    Rs.getString(2),
                    Rs.getString(3),
                    Rs.getString(4),
                    Rs.getString(5),
                    Rs.getString(6),
                    Rs.getString(7),
                    Rs.getString(8)
            });
               TPETUGAS.setModel(grid);
               TPETUGAS.enable(false);
               //BTNTAMBAH.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Gagal Tampil: "+e);
        }
     }
     private void kosongkan (){
         TXTKODEPETUGAS.setText("");
         TXTNAMAPETUGAS.setText("");
         JTANGGAL.setDate(null);
         TXTTEMPATLAHIR.setText("");
         CBJENISKELAMIN.setSelectedItem(null);
         CBJABATAN.setSelectedItem(null);
         TXTALAMAT.setText("");
         TXTNOHP.setText("");
         TXTKODEPETUGAS.requestFocus();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TXTKODEPETUGAS = new javax.swing.JTextField();
        TXTNAMAPETUGAS = new javax.swing.JTextField();
        TXTTEMPATLAHIR = new javax.swing.JTextField();
        TXTALAMAT = new javax.swing.JTextField();
        CBJENISKELAMIN = new javax.swing.JComboBox<>();
        CBJABATAN = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TPETUGAS = new javax.swing.JTable();
        TXTNOHP = new javax.swing.JTextField();
        BTNSIMPAN = new javax.swing.JButton();
        BTNEDIT = new javax.swing.JButton();
        BTNBATAL = new javax.swing.JButton();
        BTNHAPUS = new javax.swing.JButton();
        BTNKELUAR = new javax.swing.JButton();
        JTANGGAL = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/PETUGAS.png"))); // NOI18N
        jLabel1.setText("PETUGAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel2.setText("KODE PETUGAS");

        jLabel3.setText("NAMA PETUGAS");

        jLabel4.setText("TANGGAL LAHIR");

        jLabel5.setText("TEMPAT LAHIR");

        jLabel6.setText("JENIS KELAMIN");

        jLabel7.setText("JABATAN");

        jLabel8.setText("ALAMAT");

        jLabel9.setText("NO.HP");

        TXTKODEPETUGAS.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TXTKODEPETUGAS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTKODEPETUGASKeyPressed(evt);
            }
        });

        TXTNAMAPETUGAS.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TXTNAMAPETUGAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNAMAPETUGASActionPerformed(evt);
            }
        });

        TXTTEMPATLAHIR.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TXTTEMPATLAHIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTEMPATLAHIRActionPerformed(evt);
            }
        });

        TXTALAMAT.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        CBJENISKELAMIN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "LAKI - LAKI", "PEREMPUAN" }));
        CBJENISKELAMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBJENISKELAMINActionPerformed(evt);
            }
        });

        CBJABATAN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "ADMIN", "MANAGER", "STAF", "KASIR", "PETUGAS", " " }));

        TPETUGAS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TPETUGAS);

        TXTNOHP.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        BTNSIMPAN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/save.png"))); // NOI18N
        BTNSIMPAN.setText("SIMPAN");
        BTNSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSIMPANActionPerformed(evt);
            }
        });

        BTNEDIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/edit-16x16.png"))); // NOI18N
        BTNEDIT.setText("EDIT");
        BTNEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDITActionPerformed(evt);
            }
        });

        BTNBATAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/refresh-16x16.png"))); // NOI18N
        BTNBATAL.setText("BATAL");
        BTNBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBATALActionPerformed(evt);
            }
        });

        BTNHAPUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/HAPUS.png"))); // NOI18N
        BTNHAPUS.setText("HAPUS");
        BTNHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHAPUSActionPerformed(evt);
            }
        });

        BTNKELUAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/forward.png"))); // NOI18N
        BTNKELUAR.setText("KELUAR");
        BTNKELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNKELUARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTNSIMPAN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNEDIT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNBATAL)
                        .addGap(2, 2, 2)
                        .addComponent(BTNHAPUS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNKELUAR))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTANGGAL, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TXTKODEPETUGAS, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(TXTNAMAPETUGAS)
                                    .addComponent(TXTTEMPATLAHIR))))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TXTALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTNOHP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CBJABATAN, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CBJENISKELAMIN, javax.swing.GroupLayout.Alignment.TRAILING, 0, 104, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXTKODEPETUGAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBJENISKELAMIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXTNAMAPETUGAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(CBJABATAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(TXTALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JTANGGAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXTTEMPATLAHIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(TXTNOHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNEDIT)
                    .addComponent(BTNBATAL)
                    .addComponent(BTNHAPUS)
                    .addComponent(BTNKELUAR)
                    .addComponent(BTNSIMPAN))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTKODEPETUGASKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTKODEPETUGASKeyPressed
        // TODO add your handling code here:
        kodepetugas=TXTKODEPETUGAS.getText();
        int A = evt.getKeyCode();
        if (A==10){
            try {
                Sql="SELECT * FROM tb_petugas WHERE Kode_petugas='"+kodepetugas+"'";
                st=Con.createStatement();
                Rs=st.executeQuery(Sql);
                while(Rs.next()){
                    TXTNAMAPETUGAS.setText(Rs.getString(2));
                    JTANGGAL.setDate(Rs.getDate(3));
                    TXTTEMPATLAHIR.setText(Rs.getString(4));
                    CBJENISKELAMIN.setSelectedItem(Rs.getString(5));
                    CBJABATAN.setSelectedItem(Rs.getString(6));
                    TXTALAMAT.setText(Rs.getString(7));
                    TXTNOHP.setText(Rs.getString(8));
                    BTNSIMPAN.enable(false);
                    BTNEDIT.enable(true);
                    BTNHAPUS.enable(true);
                }
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(null, "Data Not Found\n"+e.getMessage());
                TXTNAMAPETUGAS.requestFocus();
            }
        }
    }//GEN-LAST:event_TXTKODEPETUGASKeyPressed

    private void TXTNAMAPETUGASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNAMAPETUGASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNAMAPETUGASActionPerformed

    private void TXTTEMPATLAHIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTEMPATLAHIRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTEMPATLAHIRActionPerformed

    private void CBJENISKELAMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBJENISKELAMINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBJENISKELAMINActionPerformed

    private void BTNSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSIMPANActionPerformed
        // TODO add your handling code here:
        kodepetugas=TXTKODEPETUGAS.getText();
        namapetugas=TXTNAMAPETUGAS.getText();
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String Tanggal = String.valueOf (fm.format(JTANGGAL.getDate()));
        tempatlahir=TXTTEMPATLAHIR.getText();
        jeniskelamin=CBJENISKELAMIN.getItemAt(CBJENISKELAMIN.getSelectedIndex());
        jabatan=CBJABATAN.getItemAt(CBJABATAN.getSelectedIndex());
        alamat=TXTALAMAT.getText();
        nohp=TXTNOHP.getText();
        try {
            Sql="INSERT INTO tb_petugas"
            + "(kode_petugas,nama_petugas,tanggal_lahir,tempat_lahir,jenis_kelamin,jabatan,alamat,nohp)"
            + "VALUES('"+kodepetugas+"',"
            + "'"+namapetugas+"',"
            + "'"+Tanggal+"',"
            + "'"+tempatlahir+"',"
            + "'"+jeniskelamin+"',"
            + "'"+jabatan+"',"
            + "'"+alamat+"',"
            + "'"+nohp+"')";
            st=Con.createStatement();
            st.execute(Sql);
            kosongkan();
            TampilPetugas("SELECT*FROM tb_petugas");
            JOptionPane.showMessageDialog(null, "Saving Succses");
            //BTNTAMBAH.show();
            BTNSIMPAN.enable(true);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Data Tidak Tersimpan\n"+e.getMessage());
        }

    }//GEN-LAST:event_BTNSIMPANActionPerformed

    private void BTNEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDITActionPerformed
        // TODO add your handling code here:
        kodepetugas=TXTKODEPETUGAS.getText();
        namapetugas=TXTNAMAPETUGAS.getText();
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String Tanggal = String.valueOf (fm.format(JTANGGAL.getDate()));
        tempatlahir=TXTTEMPATLAHIR.getText();
        jeniskelamin=CBJENISKELAMIN.getItemAt(CBJENISKELAMIN.getSelectedIndex());
        jabatan=CBJABATAN.getItemAt(CBJABATAN.getSelectedIndex());
        alamat=TXTALAMAT.getText();
        nohp=TXTNOHP.getText();
        try { Sql="UPDATE tb_petugas SET nama_petugas='"+namapetugas+"',"
            + "tanggal_lahir='"+Tanggal+"',"
            + "tempat_lahir='"+tempatlahir+"',"
            + "jenis_kelamin='"+jeniskelamin+"',"
            + "jabatan='"+jabatan+"',"
            + "alamat='"+alamat+"',"
            + "nohp='"+nohp+"'"
            + "WHERE Kode_petugas='"+kodepetugas+"'";
            st=Con.createStatement();
            st.execute(Sql);
            kosongkan();
            TampilPetugas("SELECT*FROM tb_petugas");
            JOptionPane.showMessageDialog(null, "Edit Succses");
            //BTNTAMBAH.show();
            BTNSIMPAN.show();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Data Tidak Di Perbaharui\n"+e.getMessage());
        }
    }//GEN-LAST:event_BTNEDITActionPerformed

    private void BTNBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBATALActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_BTNBATALActionPerformed

    private void BTNHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHAPUSActionPerformed
        // TODO add your handling code here:
        kodepetugas=TXTKODEPETUGAS.getText();
        try { Sql="DELETE FROM tb_petugas "
            + "WHERE Kode_petugas='" +kodepetugas+ "'";
            st=Con.createStatement();
            st.execute(Sql);
            kosongkan();
            TampilPetugas("SELECT*FROM tb_petugas");
            JOptionPane.showMessageDialog(null, "Delete Succses");
            //BTNTAMBAH.show();
            BTNSIMPAN.show();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Data Tidak Di Hapus\n"+e.getMessage());
        }

    }//GEN-LAST:event_BTNHAPUSActionPerformed

    private void BTNKELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNKELUARActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTNKELUARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Petugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBATAL;
    private javax.swing.JButton BTNEDIT;
    private javax.swing.JButton BTNHAPUS;
    private javax.swing.JButton BTNKELUAR;
    private javax.swing.JButton BTNSIMPAN;
    private javax.swing.JComboBox<String> CBJABATAN;
    private javax.swing.JComboBox<String> CBJENISKELAMIN;
    private com.toedter.calendar.JDateChooser JTANGGAL;
    private javax.swing.JTable TPETUGAS;
    private javax.swing.JTextField TXTALAMAT;
    private javax.swing.JTextField TXTKODEPETUGAS;
    private javax.swing.JTextField TXTNAMAPETUGAS;
    private javax.swing.JTextField TXTNOHP;
    private javax.swing.JTextField TXTTEMPATLAHIR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
